# Generated by Django 5.2.7 on 2025-11-27 04:50

import proveedores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(default='no-email@example.invalid', help_text='Email principal (obligatorio)', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='email_secundario',
            field=models.EmailField(blank=True, help_text='Email alternativo (opcional)', max_length=254, null=True, verbose_name='Email Secundario'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='rut_nif',
            field=models.CharField(default=2, help_text='Formato: 12345678-5 (sin puntos)', max_length=12, unique=True, validators=[proveedores.models.validar_rut_chileno], verbose_name='RUT'),
            preserve_default=False,
        ),
    ]
