# Generated by Django 5.2.7 on 2025-11-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_proveedor_email_proveedor_email_secundario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='pais',
            field=models.CharField(default='Chile', help_text='País del proveedor (obligatorio)', max_length=80, verbose_name='País'),
        ),
    ]
